### PR TITLE
hpke: rename algorithm identifiers

### PR DESCRIPTION
**Pull request by armfazh**
Now, one can name algorithms as `KEM.P256.HKDF.SHA256`.

changes:
- identifiers using structures.
- include Parsing functions for get algorithm identifiers.
- rename errors.

### CODE REVIEW

**Comment by cjpatton** [comment]
Is the purpose of this to avoid using camel case for constants? Why not `KEM_P256_HKDF_SHA256` instead?

**Comment by armfazh** [comment]
> Is the purpose of this to avoid using camel case for constants?
> Why not `KEM_P256_HKDF_SHA256` instead?

Yes, the purpose is to have an alternative to `KEM_P256_HKDF_SHA256`. 

https://golang.org/doc/effective_go.html#mixed-caps

**Comment by cjpatton** [comment]
I don't think this is a good idea, as it's not a very common design pattern and it seems like it would be hard to maintain. Better to just have a constant for each codepoint. I prefer the current camel case names, but would be fine with `KEM_P256_HKDF_SHA256`.

**Comment by armfazh** [comment]
> I don't think this is a good idea, as it's not a very common design pattern and it seems like it would be hard to maintain. Better to just have a constant for each codepoint. I prefer the current camel case names, but would be fine with `KEM_P256_HKDF_SHA256`.

Breaking the rule a bit because underscores improve clarity in this case.
see https://github.com/cloudflare/circl/pull/201

**Comment by armfazh** [comment]
closed in favour of #201

**Pull request closed without merging**
