### PR TITLE
kyber: reduce allocations

### PR DESCRIPTION
**Pull request by bwesterb**

### CODE REVIEW

**Comment by armfazh** [comment]
could you share the benchcmp diff of the changes

**Comment by bwesterb** [comment]
```
name                        old time/op  new time/op  delta
GenerateKeyPair/Kyber512-8  19.3µs ± 1%  19.3µs ± 1%    ~     (p=0.548 n=5+5)
Encapsulate/Kyber512-8      14.5µs ± 1%  14.4µs ± 1%  -1.02%  (p=0.032 n=5+5)
Decapsulate/Kyber512-8      15.5µs ± 8%  14.5µs ± 2%  -6.10%  (p=0.016 n=5+5)
```

**Comment by bwesterb** [comment]
(The real advantage, though, is probably higher than shown in such a benchmark — cf. #282)

**Comment by armfazh** [comment]
Enable `-benchmem` flag to see the improvements in memory allocs.

**Comment by bwesterb** [comment]
```
name                        old allocs/op  new allocs/op  delta
GenerateKeyPair/Kyber512-8      7.00 ± 0%      5.00 ± 0%   ~     (p=1.000 n=1+1)
Encapsulate/Kyber512-8          6.00 ± 0%      3.00 ± 0%   ~     (p=1.000 n=1+1)
Decapsulate/Kyber512-8          3.00 ± 0%      1.00 ± 0%   ~     (p=1.000 n=1+1)
bas@C02FW0C1ML7J ~/scm/circl/kem/schemes $ 
```

**Review by armfazh — APPROVED** [review]

**Pull request merged**
